import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "doc",
      id: "docs/index",
      label: "Bem-vindo à V3",
    },
    {
      type: "category",
      label: "Conheça a V3",
      link: {
        type: "generated-index",
        title: "Conheça a V3",
        description:
          "Entenda quem somos, como usamos tecnologia e para quem construímos a plataforma.",
        slug: "/docs/category/conheca-a-v3",
      },
      items: [
        "docs/conheca-a-v3/quem-somos",
        "docs/conheca-a-v3/como-usamos-a-tecnologia",
        "docs/conheca-a-v3/publico-alvo",
      ],
    },
    {
      type: "category",
      label: "Visão Geral da Plataforma",
      link: {
        type: "generated-index",
        title: "Visão Geral da Plataforma",
        description:
          "Entenda a V3 e os componentes da solução antes de iniciar a implementação.",
        slug: "/docs/category/visao-geral-da-plataforma",
      },
      items: [
        "docs/visao-geral-da-plataforma/missao-visao-valores",
        {
          type: "autogenerated",
          dirName: "docs/visao-geral-da-plataforma/solucao-v3",
        },
      ],
    },
    {
      type: "category",
      label: "Implantação e Setup",
      link: {
        type: "generated-index",
        title: "Implantação e Setup",
        description:
          "Prepare o ambiente e execute a implantação com os guias operacionais da V3.",
        slug: "/docs/category/implantacao-e-setup",
      },
      items: [
        "docs/implantacao-e-setup/configuracao-inicial",
        {
          type: "autogenerated",
          dirName: "docs/implantacao-e-setup/manual-de-instalacao",
        },
        "docs/implantacao-e-setup/ferramenta-de-configuracao",
      ],
    },
    {
      type: "category",
      label: "Integração e Operação",
      link: {
        type: "generated-index",
        title: "Integração e Operação",
        description:
          "Implemente autenticação, permissões e integrações operacionais com os módulos da plataforma.",
        slug: "/docs/category/integracao-e-operacao",
      },
      items: [
        {
          type: "category",
          label: "API",
          items: [
            "docs/integracao-e-operacao/ap/autenticacao",
            "docs/integracao-e-operacao/ap/permissionamento",
            "docs/integracao-e-operacao/ap/gerenciamento",
            "docs/integracao-e-operacao/ap/ordens",
            "docs/integracao-e-operacao/ap/eventos",
            "docs/integracao-e-operacao/ap/visoes",
            "docs/integracao-e-operacao/ap/notificacoes",
          ],
        },
        {
          type: "category",
          label: "SDKs",
          items: [
            "docs/integracao-e-operacao/sdks/index",
            "docs/integracao-e-operacao/sdks/java",
            "docs/integracao-e-operacao/sdks/kotlin",
            "docs/integracao-e-operacao/sdks/dotnet",
            "docs/integracao-e-operacao/sdks/go",
          ],
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: "category",
      label: "Order",
      link: {
        type: "generated-index",
        title: "Order API",
        description:
          "This is the orders API. It contains all the endpoints related to orders.",
        slug: "/category/order-api",
      },
      items: require("./docs/openapi/order/sidebar"),
    },
    {
      type: "category",
      label: "Management",
      link: {
        type: "generated-index",
        title: "Management API",
        description:
          "This is the management API. It contains all the endpoints related to management.",
        slug: "/category/management-api",
      },
      items: require("./docs/openapi/management/sidebar"),
    },
    {
      type: "category",
      label: "Auth",
      link: {
        type: "generated-index",
        title: "Auth API",
        description:
          "Go service that acts as a proxy for authentication and token verification with Keycloak, providing simplified endpoints for obtaining and validating JWT tokens.",
        slug: "/category/auth-api",
      },
      items: require("./docs/openapi/auth/sidebar"),
    },
    {
      type: "category",
      label: "Event",
      link: {
        type: "generated-index",
        title: "Event API",
        description:
          "This is the event API. It contains all the endpoints related to event.",
        slug: "/category/event-api",
      },
      items: require("./docs/openapi/event/sidebar"),
    },
    {
      type: "category",
      label: "Notifications",
      link: {
        type: "generated-index",
        title: "Notifications Webhook",
        description:
          "This is the notifications Webhook. It contains how to implement a HTTP POST to listen Notifications",
        slug: "category/notification-webhook",
      },
      items: [require("./docs/openapi/notification/sidebar"), require("./docs/webhook/subscription/sidebar")],
    },
    {
      type: "category",
      label: "Vision",
      link: {
        type: "generated-index",
        title: "Vision API",
        description:
          "This is the vision API. It contains all the endpoints related to vision.",
        slug: "/category/vision-api",
      },
      items: require("./docs/openapi/vision/sidebar"),
    },
    {
      type: "category",
      label: "Medias",
      link: {
        type: "generated-index",
        title: "Media API",
        description:
          "This is the media API. It contains all the endpoints related to media.",
        slug: "/category/media-api",
      },
      items: [require("./docs/openapi/media/sidebar"), require("./docs/openapi/media-stream/sidebar")],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
