import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: "doc", id: "intro" },
    { type: "autogenerated", dirName: "tutorial-basics" },
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
  orderApiSidebar: [
    {
      type: "category",
      label: "Orders",
      link: {
        type: "generated-index",
        title: "Orders API",
        description:
          "This is the orders API. It contains all the endpoints related to orders.",
          slug: "/category/orders-api",
      },
      items: require("./docs/openapi/orders/sidebar")
    },
    {
      type: "category",
      label: "Management",
      link: {
        type: "generated-index",
        title: "Management API",
        description:
          "This is the management API. It contains all the endpoints related to management.",
          slug: "/category/management-api",
      },
      items: require("./docs/openapi/managements/sidebar")
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
