basePath: /v1
definitions:
  auth.VerifyResponse:
    properties:
      claims: {}
      message:
        type: string
      valid:
        type: boolean
    type: object
  model.RefreshToken:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      not-before-policy:
        type: integer
      refresh_expires_in:
        type: integer
      refresh_token:
        type: string
      scope:
        type: string
      session_state:
        type: string
      token_type:
        type: string
    type: object
  response.RealmAccess:
    properties:
      roles:
        items:
          type: string
        type: array
    type: object
  response.StandardError:
    properties:
      error:
        type: string
      error_description:
        type: string
    type: object
  response.TokenPayload:
    properties:
      access_token:
        type: string
      account_id:
        type: string
      active:
        type: boolean
      client_id:
        type: string
      expires_in:
        type: integer
      iat:
        type: integer
      jti:
        type: string
      realm_access:
        $ref: '#/definitions/response.RealmAccess'
      refresh_token:
        type: string
      scope:
        type: string
      session_state:
        type: string
      tenant_id:
        type: string
      token_type:
        type: string
      username:
        type: string
    type: object
host: tenant.v3sandbox.com
info:
  contact: {}
  description: Serviço de autenticação que oferece endpoints simplificados para
    obtenção e validação de tokens de acesso.
  title: Auth API
  version: 0.0.1
paths:
  /auth/token:
    get:
      consumes:
      - application/json
      description: |-
        Este endpoint permite validar um token de autenticação existente.
        Quando um token é enviado, o sistema verifica se ele ainda é válido e confiável.
        Em caso de sucesso, retorna uma resposta JSON com os detalhes do token (claims).
        Se o token for inválido, expirado ou malformado, um erro estruturado é retornado.
      parameters:
      - description: Token Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            $ref: '#/definitions/auth.VerifyResponse'
        "401":
          description: Não autorizado
          schema:
            $ref: '#/definitions/response.StandardError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/response.StandardError'
      operationId: validar-token-de-autenticacao
      summary: Validar token de autenticação
      tags:
      - Auth
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        Gera um token de autenticação a partir das credenciais fornecidas.
        Em caso de sucesso, retorna o token gerado em formato JSON.
        Se a geração falhar, uma resposta de erro estruturada é retornada com o código
        de status e a mensagem apropriados.
        Para mais informações, consulte a documentação de autenticação em
        https://developer.v3control.com/docs/docs/autenticacao
      parameters:
      - description: Tipo de concessão
        in: formData
        name: grant_type
        required: true
        type: string
      - description: Escopo
        in: formData
        name: scope
        required: true
        type: string
      - description: ID do cliente
        in: formData
        name: client_id
        required: true
        type: string
      - description: Segredo do cliente
        in: formData
        name: client_secret
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            $ref: '#/definitions/response.TokenPayload'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/response.StandardError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/response.StandardError'
      operationId: gerar-token
      summary: Gerar token
      tags:
      - Auth
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        Este endpoint permite renovar um token de autenticação existente.
        Quando um refresh token é enviado, o sistema verifica se ele ainda é válido e confiável.
        Em caso de sucesso, retorna uma resposta JSON com os detalhes do novo token de acesso
        e metadados relacionados.
        Se o token for inválido, expirado ou malformado, um erro estruturado é retornado.
        Para renovar um token, informe o refresh token via form data.
      parameters:
      - description: Refresh token válido
        in: formData
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            $ref: '#/definitions/model.RefreshToken'
        "400":
          description: 'Requisição inválida: dados do formulário inválidos ou ausentes'
          schema:
            $ref: '#/definitions/response.StandardError'
        "401":
          description: 'Não autorizado: refresh token inválido ou expirado'
          schema:
            $ref: '#/definitions/response.StandardError'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/response.StandardError'
      operationId: renovar-token-de-autenticacao
      summary: Renovar token de autenticação
      tags:
      - Auth
schemes:
- https
swagger: "2.0"

