basePath: /v1
definitions:
  dto.WebhookRequest:
    properties:
      event_names:
        items:
          type: string
        type: array
      name:
        type: string
      url:
        type: string
    type: object
  dto.WebhookResponse:
    properties:
      created_at:
        type: string
      event_names:
        items:
          $ref: '#/definitions/model.EventName'
        type: array
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
  model.Category:
    properties:
      subs:
        items:
          type: string
        type: array
      type:
        type: string
    type: object
  model.EventName:
    properties:
      category:
        items:
          $ref: '#/definitions/model.Category'
        type: array
      type:
        type: string
    type: object
host: tenant.v3sandbox.com
info:
  contact: {}
  description: Serviço responsável por gerenciar webhooks para clientes.
  title: Notifications API
  version: 0.0.1
paths:
  /notifications/webhooks:
    get:
      consumes:
      - application/json
      description: Retorna todos os webhooks registrados para o tenant
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            items:
              $ref: '#/definitions/dto.WebhookResponse'
            type: array
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      operationId: listar-webhooks-do-tenant
      summary: Listar webhooks do tenant
      tags:
      - Webhook
    post:
      consumes:
      - application/json
      description: Cria um webhook associado ao tenant informado
      parameters:
      - description: Dados do webhook
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.WebhookRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Criado
          schema:
            $ref: '#/definitions/dto.WebhookResponse'
        "400":
          description: Requisição inválida
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      operationId: criar-webhook-para-o-tenant
      summary: Criar webhook para o tenant
      tags:
      - Webhook
  /notifications/webhooks/{id}:
    delete:
      consumes:
      - application/json
      description: Remove um webhook do tenant
      parameters:
      - description: ID do webhook
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Sem conteúdo
          schema:
            type: string
        "400":
          description: Requisição inválida
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      operationId: remover-webhook
      summary: Remover webhook
      tags:
      - Webhook
    get:
      consumes:
      - application/json
      description: Retorna os dados de um webhook específico do tenant
      parameters:
      - description: ID do webhook
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            $ref: '#/definitions/dto.WebhookResponse'
        "400":
          description: Requisição inválida
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Não encontrado
          schema:
            additionalProperties:
              type: string
            type: object
      operationId: obter-webhook-por-id
      summary: Obter webhook por ID
      tags:
      - Webhook
    put:
      consumes:
      - application/json
      description: Atualiza os dados de um webhook do tenant
      parameters:
      - description: ID do webhook
        in: path
        name: id
        required: true
        type: string
      - description: Dados do webhook
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.WebhookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            $ref: '#/definitions/dto.WebhookResponse'
        "400":
          description: Requisição inválida
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      operationId: atualizar-webhook
      summary: Atualizar webhook
      tags:
      - Webhook
schemes:
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Bearer Token
    type: apiKey
swagger: "2.0"

