basePath: /v1
definitions:
  response.Error:
    properties:
      code:
        type: string
      details:
        items: {}
        type: array
      message:
        type: string
    type: object
  response.Meta:
    properties:
      request_id:
        type: string
      timestamp:
        type: string
    type: object
  response.VisionErrorResponse:
    properties:
      error:
        $ref: '#/definitions/response.Error'
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
  response.VisionResponse:
    type: object
host: v3sandbox.com
info:
  contact: {}
  description: |-
    The Vision context serves as the central processing hub for events received by V3CLOUD, enabling computer vision inference.
    Computer vision is a field of artificial intelligence that allows computers to interpret and extract information from images and videos, simulating human vision.
    This solution is designed to act as a processing engine for events arriving at the Cloud.
    All incoming events are monitored by an agent.
  title: Vision API
  version: 0.0.1
paths:
  /datasets:
    post:
      consumes:
      - application/json
      description: Creates a new dataset with the provided details.
      parameters:
      - description: Dataset details
        in: body
        name: payload
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Dataset created successfully
          schema:
            $ref: '#/definitions/response.VisionResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create new dataset
      tags:
      - Datasets
  /datasets/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a dataset by its ID.
      parameters:
      - description: Dataset ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Dataset deleted successfully
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "404":
          description: Dataset not found
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete dataset by ID
      tags:
      - Datasets
    get:
      consumes:
      - application/json
      description: Retrieves a dataset by its ID.
      parameters:
      - description: Dataset ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Dataset retrieved successfully
          schema:
            $ref: '#/definitions/response.VisionResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "404":
          description: Dataset not found
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get dataset by ID
      tags:
      - Datasets
    put:
      consumes:
      - application/json
      description: Updates an existing dataset by its ID.
      parameters:
      - description: Dataset ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated dataset details
        in: body
        name: payload
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Dataset updated successfully
          schema:
            $ref: '#/definitions/response.VisionResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "404":
          description: Dataset not found
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update dataset by ID
      tags:
      - Datasets
  /media/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves media by its ID.
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Media retrieved successfully
          schema:
            $ref: '#/definitions/response.VisionResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "404":
          description: Media not found
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.VisionErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get media by ID
      tags:
      - Media
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Bearer Token
    type: apiKey
swagger: "2.0"
