basePath: /
definitions:
  main.EventResponse:
    properties:
      message:
        type: string
    type: object
  main.WebhookPayload:
    type: object
    required:
      - id
      - created_at
      - attributes
    properties:
      id:
        type: string
        description: ULID do Webhook
      created_at:
        type: string
        format: date-time
        description: Data de criação do Webhook
      attributes:
        type: array
        items:
          $ref: '#/definitions/model.Event'
        description: Lista de Eventos associados ao Webhook
  model.Event:
    type: object
    required:
      - id
      - created_at
      - type
      - sub
    properties:
      id:
        type: string
        description: ULID do Evento
      created_at:
        type: string
        format: date-time
        description: Data de criação do Evento no Firmeware
      type:
        type: string
        enum:
          - "ORDER"
          - "EVENT"
        description: Tipo do Evento
        x-enum-varnames:
          - "ORDER"
          - "EVENT"
      sub:
        type: string
        enum:
          - "STATUS"
          - "UPLOAD"
        description: Subtipo do Evento
        x-enum-varnames:
          - "STATUS"
          - "UPLOAD"
      trip_id:
        type: string
        description: ULID da Trip associada ao Evento
      attributes:
        type: array
        items:
          type: object
          required:
            - device
          properties:
            device:
              $ref: '#/definitions/model.Device'
              description: Dispositivo associado ao Evento
            order:
              $ref: '#/definitions/model.Order'
              description: Order associada ao Evento
            files:
              type: array
              items:
                $ref: '#/definitions/model.File'
              description: Lista de arquivos associados ao Evento
  model.Device:
    type: object
    required:
      - id
      - imei
    properties:
      id:
        type: string
        description: ULID do dispositivo na API
      correlation_id:
        type: string
        format: ulid
        description: ULID de correlação do Dispositivo
      imei:
        type: string
        description: IMEI do Dispositivo
  model.Order:
    type: object
    required:
      - id
      - created_at
      - updated_at
    properties:
      id:
        type: string
        description: ULID da Order
      correlation_id:
        type: string
        format: ulid
        description: ULID de correlação da Order
      group:
        type: string
        enum:
            - "COMMAND"
            - "CONFIG"
        x-enum-varnames:
            - "COMMAND"
            - "CONFIG"
        description: Grupo da Order
      status:
        type: string
        enum:
          - "DELETED"
          - "PROCESSED"
          - "FAILED"
          - "SENT"
          - "PENDING"
          - "NACK"
          - "ACK"
        x-enum-varnames:
          - "DELETED"
          - "PROCESSED"
          - "FAILED"
          - "SENT"
          - "PENDING"
          - "NACK"
          - "ACK"
        description: Status da Order
      type:
        type: string
        enum:
          - "ADD_WIFI"
          - "DELETE_WIFI"
          - "DEVICE_STATE"
          - "REQUEST_IMAGE"
          - "REQUEST_VIDEO"
          - "CONFIG"
          - "REBOOT"
          - "DRIVER_COACH_INERTIAL"
          - "DRIVER_COACH_TELEMETRY"
          - "DRIVER_COACH_TRACKING"
          - "INTERNAL"
        x-enum-varnames:
          - "ADD_WIFI"
          - "DELETE_WIFI"
          - "DEVICE_STATE"
          - "REQUEST_IMAGE"
          - "REQUEST_VIDEO"
          - "CONFIG"
          - "REBOOT"
          - "DRIVER_COACH_INERTIAL"
          - "DRIVER_COACH_TELEMETRY"
          - "DRIVER_COACH_TRACKING"
          - "INTERNAL"
        description: Tipo de Order
      created_at:
        type: string
        format: date-time
        description: Data de criação da Order
      updated_at:
        type: string
        format: date-time
        description: Data da última atualização da Order
      deleted_at:
        type: string
        format: date-time
        description: Data de exclusão da Order
  model.File:
    type: object
    required:
      - id
      - url
      - metadata
    properties:
      id:
        type: string
        description: ULID da Mídia
      url:
        type: string
        description: URL da Mídia
      metadata:
        $ref: '#/definitions/model.FileMetadata'
        description: Metadados da Mídia
  model.FileMetadata:
    type: object
    required:
      - content_type
      - file_size
    properties:
      width:
        type: integer
        description: Largura da mídia em pixels
      height:
        type: integer
        description: Altura da mídia em pixels
      compression:
        type: string
        description: Tipo de compressão da mídia
      quality:
        type: integer
        description: Qualidade da mídia (0-100)
      cam_channel:
        type: string
        description: Canal da câmera
      content_type:
        type: string
        description: Tipo de conteúdo da mídia (MIME)
      file_size:
        type: integer
        description: Tamanho do arquivo em bytes
host: yourcompany.com
info:
  contact: {}
  description: That is a webhook service for notifications.
  title: notification-service
  version: 0.0.1
paths:
  /webhook:
    post:
      consumes:
      - application/json
      parameters:
      - name: X-V3-Signature
        in: header
        description: HMAC Header to validate
        required: true
        schema:
          type: string
      - description: Webhook Payload
        in: body
        name: payload
        schema:
          $ref: '#/definitions/main.WebhookPayload'
          required: true
      produces:
      - application/json
      responses:
        "200":
          description: Event message received!
          schema:
            $ref: '#/definitions/main.EventResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Webhook
      tags:
      - Webhook
schemes:
- https
swagger: "2.0"
