basePath: /
definitions:
  main.EventResponse:
    properties:
      message:
        type: string
    type: object
  main.WebhookPayload:
    type: object
    required:
      - id
      - created_at
      - attributes
    properties:
      id:
        type: string
        description: ULID of the Webhook
      created_at:
        type: string
        format: date-time
        description: Webhook creation date
      attributes:
        type: array
        items:
          $ref: '#/definitions/model.Event'
          description: List of events associated with the Webhook
  model.Event:
    type: object
    required:
      - id
      - created_at
      - type
      - sub
    properties:
      id:
        type: string
        description: ULID of the Event
      created_at:
        type: string
        format: date-time
        description: Event creation date in the Firmware
      type:
        type: string
        enum:
          - "ORDER"
          - "EVENT"
        description: Event type
        x-enum-varnames:
          - "ORDER"
          - "EVENT"
      sub:
        type: string
        enum:
          - "STATUS"
          - "UPLOAD"
          - "DMS"
          - "DRIVER_BEHAVIOR"
          - "TELEMETRY"
          - "ADAS"
        description: Event subtype
        x-enum-varnames:
          - "STATUS"
          - "UPLOAD"
          - "DMS"
          - "DRIVER_BEHAVIOR"
          - "TELEMETRY"
          - "ADAS"
      trip_id:
        type: string
        description: ULID of the Trip associated with the Event
      attributes:
        type: array
        items:
          type: object
          required:
            - device
          properties:
            device:
              $ref: '#/definitions/model.Device'
              description: Device associated with the Event
            order:
              $ref: '#/definitions/model.Order'
              description: Order associated with the Event
            data:
              properties:
                files:
                  type: array
                  items:
                    $ref: '#/definitions/model.File'
                  description: List of files associated with the Event
              type: object
              description: Event data
  model.Device:
    type: object
    required:
      - id
      - imei
    properties:
      id:
        type: string
        description: Device ULID in the API
      correlation_id:
        type: string
        format: ulid
        description: Device correlation ULID
      imei:
        type: string
        description: Device IMEI
  model.Order:
    type: object
    required:
      - id
      - created_at
      - updated_at
    properties:
      id:
        type: string
        description: ULID of the Order
      correlation_id:
        type: string
        format: ulid
        description: Order correlation ULID
      group:
        type: string
        enum:
            - "COMMAND"
            - "CONFIG"
        x-enum-varnames:
            - "COMMAND"
            - "CONFIG"
        description: Order group
      status:
        type: string
        enum:
          - "PENDING"
          - "SENT"
          - "FAILED"
          - "ACK"
          - "NACK"
        x-enum-varnames:
          - "PENDING"
          - "SENT"
          - "FAILED"
          - "ACK"
          - "NACK"
        description: Order status
      type:
        type: string
        enum:
          - "ADD_WIFI"
          - "DELETE_WIFI"
          - "DEVICE_STATE"
          - "REQUEST_IMAGE"
          - "REQUEST_VIDEO"
          - "CONFIG"
          - "REBOOT"
          - "DRIVER_COACH_INERTIAL"
          - "DRIVER_COACH_TELEMETRY"
          - "DRIVER_COACH_TRACKING"
          - "INTERNAL"
        x-enum-varnames:
          - "ADD_WIFI"
          - "DELETE_WIFI"
          - "DEVICE_STATE"
          - "REQUEST_IMAGE"
          - "REQUEST_VIDEO"
          - "CONFIG"
          - "REBOOT"
          - "DRIVER_COACH_INERTIAL"
          - "DRIVER_COACH_TELEMETRY"
          - "DRIVER_COACH_TRACKING"
          - "INTERNAL"
        description: Order type
      created_at:
        type: string
        format: date-time
        description: Order creation date
      updated_at:
        type: string
        format: date-time
        description: Order last update date
      deleted_at:
        type: string
        format: date-time
        description: Order deletion date
  model.File:
    type: object
    required:
      - id
      - url
      - metadata
    properties:
      id:
        type: string
        description: Media ULID
      url:
        type: string
        description: Media URL
      metadata:
        $ref: '#/definitions/model.FileMetadata'
        description: Media metadata
  model.FileMetadata:
    type: object
    required:
      - content_type
      - file_size
    properties:
      width:
        type: integer
        description: Media width in pixels
      height:
        type: integer
        description: Media height in pixels
      compression:
        type: string
        description: Media compression type
      quality:
        type: integer
        description: Media quality (0-100)
      cam_channel:
        type: string
        description: Camera channel
      content_type:
        type: string
        description: Media content type (MIME)
      file_size:
        type: integer
        description: File size in bytes
host: yourcompany.com
paths:
  /event:
    post:
      consumes:
      - application/json
      parameters:
      - name: X-V3-Signature
        in: header
        description: HMAC Header to validate
        required: true
        schema:
          type: string
      - description: Webhook Payload
        in: body
        name: payload
        schema:
          $ref: '#/definitions/main.WebhookPayload'
          required: true
      produces:
      - application/json
      responses:
        "200":
          description: Event message received!
          schema:
            $ref: '#/definitions/main.EventResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Events
      tags:
      - Subscriptions
schemes:
- https
swagger: "2.0"
